### PR TITLE
Fix icelake marches

### PR DESCRIPTION
**Pull request by danog**
The `icelake` march actually doesn't exist, only the `icelake-server` and `icelake-client` variants exist.

### CODE REVIEW

**Comment by ptr1337** [comment]
Good catch, would you mind also to upstream the patch to the official architecutre repository from graysky?

**Comment by ptr1337** [comment]
https://github.com/graysky2/kernel_compiler_patch

**Comment by danog** [comment]
@ptr1337 Sure, but actually, I don't really like the current approach of arch selection at all: I consider this to be a hotfix, because there is a large number of arches supported by both rustc and gcc/clang that isn't listed here; the best solution should just be something autogenerated, but there are some subarch-dependent config flags that are a bit cryptic and I can't quite tell how they could be autogenerated.

For example, I was thinking of completely dropping all MARCH variants (except for a few like the amd ones that require  -mno-tbm), and specifying a string config flag that allows passing in raw rust/C compilation flags (which would be really neat to work with in combination with https://github.com/hartwork/resolve-march-native, and would allow further optimization like `l1/2-cache-size` flags).

However, this may not work well with configs like `X86_L1_CACHE_SHIFT`, `X86_INTEL_USERCOPY`, `X86_USE_PPRO_CHECKSUM`, unless there's a simple way to extract the correct value for those config flags from a custom passed -march...

(also ping @graysky2)

**Comment by danog** [comment]
I added this MR since I need optimized builds specifically for icelake, zen2/3/4 and alderlake, but a more universal solution would be much better I think...

**Review by sirlucjan — CHANGES_REQUESTED** [review]
Please fix this patch error:

```patch: **** malformed patch at line 514: +      help```

**Comment by danog** [comment]
This should do it

**Comment by sirlucjan** [comment]
Yes, thanks.

**Comment by 1Naim** [comment]
https://github.com/CachyOS/linux/commit/a1cc72e5c0da323f8d6007214dc88637a2d54a54 Queued for the next sync. Expect to see this in the repository some time next week. Thank you.

**Pull request closed without merging**
