### PR TITLE
6.8: Updated NTsync5 to v4 version

### PR DESCRIPTION
**Pull request by Artewar67**
Solves wine hang problem with ntsync patch
https://lore.kernel.org/all/20240416010837.333694-1-zfigura@codeweavers.com/ (need the first three patches from v3 version)

### CODE REVIEW

**Comment by Artewar67** [comment]
Okay

**Comment by ptr1337** [comment]
Applied on 6.8 and 6.9:
https://github.com/CachyOS/kernel-patches/commit/c6e17e01f6475a1ce29b03827091a9d757a7a7b2

**Comment by ptr1337** [comment]
@Artewar67 
Did you test this?
Multiple users complaining about a not working NTSYNC after updating to this ntsync version.

**Comment by Artewar67** [comment]
Yes I tested it and it works with wine-tkg-git

**Comment by Artewar67** [comment]
Looked into the problem a bit and found out that it is related to an old version of ntsync for proton-cachyos. It uses fastsync4 while the kernel module is updated to ntsync5. So far ntsync5 is absolutely not compatible with fsync and esync so you can revert this patch.

**Comment by ptr1337** [comment]
> Looked into the problem a bit and found out that it is related to an old version of ntsync for proton-cachyos. It uses fastsync4 while the kernel module is updated to ntsync5. So far ntsync5 is absolutely not compatible with fsync and esync so you can revert this patch.

Thats fine, since it uses as depends "winesync-dkms".

**Comment by Artewar67** [comment]
I will try to install linux-tkg and compile wine-tkg-git again to check what might be wrong.
Before that I used linux-cachyos-bore from AUR and my ntsync patch, after my ntsync was merged to your repository I just compiled linux-cachyos-bore without third party patches.

**Comment by Nanotwerp** [comment]
> Solves wine hang problem with ntsync patch https://lore.kernel.org/all/20240416010837.333694-1-zfigura@codeweavers.com/ (need the first three patches from v3 version)

Ooh, this is interesting. Where is it said that some patches from v3 should be used in tandem with v4? Also, what programs have you tested it with, and do you get the `wine: using fast synchronization` message?

**Comment by Artewar67** [comment]
> Ooh, this is interesting. Where is it said that some patches from v3 should be used in tandem with v4?

First three patch have been merged in linux-next tree.

> Also, what programs have you tested it with, and do you get the wine: using fast synchronization message?

I ran just winecfg and the terminal froze, I couldn't even close it with ctrl+c only closed the terminal completely. The message `wine: using fast synchronization` did not appear.

**Comment by Nanotwerp** [comment]
> > Ooh, this is interesting. Where is it said that some patches from v3 should be used in tandem with v4?
> 
> First three patch have been merged in linux-next tree.
> 
> > Also, what programs have you tested it with, and do you get the wine: using fast synchronization message?
> 
> I ran just winecfg and the terminal froze, I couldn't even close it with ctrl+c only closed the terminal completely. The message `wine: using fast synchronization` did not appear.

Wait, I'm confused. I thought you said it *solves* the issue!

**Comment by Nanotwerp** [comment]
> I thought you meant the old ntsync patch.

So with the new patch, does everything work fine and `wine: using fast synchronization` shows up?

**Comment by Artewar67** [comment]
With the new ntsync I have tested many games (Pacific drive, generation zero, bloons td6 and few other unity games)
Also the message wine: use fast sync synchronization appears

**Comment by Nanotwerp** [comment]
> With the new ntsync I have tested many games (Pacific drive, generation zero, bloons td6 and few other unity games) and all work properly Also the message wine: use fast sync synchronization appears

Ooh, this is interesting! I do see some slight differences between the patches on `Lore`/`zf.git` and the [patch](https://github.com/CachyOS/kernel-patches/commit/1761acdec8ea19de190c240edf73217169079b4b) posted in CachyOS' kernel patches, especially the switch from `atomic_try_cmpxchg` to `atomic_cmpxchg`. I'm wondering where @ptr1337 got that change from. I'll test it out to see if that fixes things. Is the Cachy patch the one that you're using right now?

**Comment by ptr1337** [comment]
> I'm wondering where @ptr1337

This patch came from ZF's git a while ago. This patch appears to work without problems tested by several users.
The PR here, did change from 'atomic_cmpxchg' to 'atomic_try_cmpxchg'.

We don't use the above PR'd patch anymore in 6.9, since people reported on mass that this one is not working and this https://github.com/CachyOS/kernel-patches/commit/1761acdec8ea19de190c240edf73217169079b4b does fix it.

**Comment by Nanotwerp** [comment]
> > I'm wondering where @ptr1337
> 
> 
> 
> This patch came from ZF's git a while ago. This patch appears to work without problems tested by several users.
> 
> The PR here, did change from 'atomic_cmpxchg' to 'atomic_try_cmpxchg'.
> 
> 
> 
> We don't use the above PR'd patch anymore in 6.9, since people reported on mass that this one is not working and this https://github.com/CachyOS/kernel-patches/commit/1761acdec8ea19de190c240edf73217169079b4b does fix it.
> 
> 
> 
>  

Oh, this makes sense. I'm assuming this was grabbed from Elizabeth's `zf` kernel tree? I guess it's probably lost to history with the exception of the recent patch you committed, as she probably rebased.

**Pull request closed without merging**
