### PR TITLE
6.6: Added RT to v6.6-rc1-rt1

### PR DESCRIPTION
**Pull request by MichaelDeets**
Based on [v6.6-rc1-rt1](https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/tag/?h=v6.6-rc1-rt1)
Removed patches related to ARM
Removed EXPERT requirement for PREEMPT_RT

### CODE REVIEW

**Comment by ptr1337** [comment]
Did you test it?

**Comment by MichaelDeets** [comment]
I've only tested LRNG, but I'm just compiling a new build with RT patches, is this enough or should I also use PREEMPT_RT? currently using just PREEMPT

**Comment by ptr1337** [comment]
> I've only tested LRNG, but I'm just compiling a new build with RT patches, is this enough or should I also use PREEMPT_RT? currently using just PREEMPT

We don't really provide LRNG anymore, since it mostly just did bring issues and no improvement for most users.
I think it would be better to enable PREEMPT_RT, but generally if the default one goes through, the other one does also :)

**Comment by MichaelDeets** [comment]
OK will come back once I've tested, I'll close the LRNG PR too

**Comment by ptr1337** [comment]
> OK will come back once I've tested, I'll close the LRNG PR too

We can keep LRNG in here. This is not a problem. 
I did just mean the support inside of the PKBUILD.

**Comment by ptr1337** [comment]
@MichaelDeets 

Sorry. I thought LRNG was dropped from our PKGBUILD. but I was wrong.
Everything fine!

**Comment by MichaelDeets** [comment]
OK no problem! I am currently using 6.6-rc1 with RT patches and PREEMPT_RT, it compiled fine and it seems functional for now.

**Pull request merged**
