### PR TITLE
Add Patch That Fixes Unusability At Higher Resolutions With Higher Framerates.

### PR DESCRIPTION
**Pull request by ACupOfLinux**
This patch adds code to the kernel that lowers to pixelclock for the resolution of 5120x1440@240 > 5120x1440@239.63. This helps users with ultrawide monitors. This does not NEED to be merged but it would be a QOL for people like me instead of having to build the kernel from scratch constantly. :)

### CODE REVIEW

**Comment by ptr1337** [comment]
Hi @ACupOfLinux 

Thanks for this PR!
We will review this patch and think about integrating this.
Did you also thought about sending this patch to the upstream kernel (e.g lkml?)

We generally also prefer to have some reviews from more expierenced developers, before merging stuff.
Generally these changes look fine to me, will do some compilation tests.

**Comment by ACupOfLinux** [comment]
I have not thought about that but I might give it a shot thanks for looking into this issue :)

**Comment by TheWyn** [comment]
Works as intended here, also to note there is already a similar fix for 3440x1440@100 (99.96)

**Comment by ACupOfLinux** [comment]
@TheWyn Ok great! Thanks for testing.

**Comment by 1Naim** [comment]
Hi! I did some looking around of this issue and found that an AMD dev made an updated patch of this [here](https://gitlab.freedesktop.org/drm/amd/-/issues/1442#note_2100617). If we want to include this somewhere, it would likely be this version instead of the one attached in OP. @ACupOfLinux @TheWyn can you test this patch?

**Comment by ACupOfLinux** [comment]
@1Naim I'm Currently building I'll let you know how it goes :)

**Comment by ACupOfLinux** [comment]
@1Naim Kernel Builds, and patch works as intended.

**Comment by 1Naim** [comment]
Great! It looks like Harry went and [sent](https://lore.kernel.org/all/20231101210037.130494-1-hamza.mahfooz@amd.com/t/#u) in the patch for review and there were some concerns being raised. I'll try to address them by asking people in the community with other hardware and see how it goes.

**Comment by 1Naim** [comment]
If you know of anyone with the same monitor but using an NVIDIA (or even Intel) GPU with the same driver, can you ask them to try out the kernel build with that patch too? It would help greatly.

**Comment by ACupOfLinux** [comment]
@TheWyn Ok ill see if I can find someone :)

**Comment by ACupOfLinux** [comment]
@TheWyn Ok so it seems this might already be build into Nvidia Open Kernel Modules: https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/238

**Comment by ACupOfLinux** [comment]
> If you know of anyone with the same monitor but using an NVIDIA (or even Intel) GPU with the same driver, can you ask them to try out the kernel build with that patch too? It would help greatly.

"Reddit User (leifayah) states: 
Just tried again for fun on latest Ubuntu LTS with latest Nvidia drivers with a RTX 3060 through DP.
3840x1080 119.97 + 239.97 59.97
5120x1440 239.76* 120.00 59.98
2560x1440 239.90 120.00 59.95
2560x1080 119.88 60.00 59.94
1920x1080 119.88 60.00 59.94
Works like a charm."

 So i think this is just an AMD Issue

**Comment by 1Naim** [comment]
Since this patch affects all drivers and connectors, I want to make sure that using this patch on other GPUs wouldn't cause any regressions.

**Comment by ACupOfLinux** [comment]
> Since this patch affects all drivers and connectors, I want to make sure that using this patch on other GPUs wouldn't cause any regressions.

I'll try and find someone on reddit or some internet fourm :)

**Comment by 1Naim** [comment]
To my surprise, @TheWyn and another user in our discord community also has the same monitor with an NVIDIA GPU. Suffice to say, everything seems to work as they should be so we will likely queue this for the next 6.11 and the next 6.12 release. 6.12 in particular just released 6.12rc4 earlier today, so the next update will likely include this. Thank you again for bringing this patch out to us.

**Comment by 1Naim** [comment]
I have applied the patch from LKML to both 6.11 and 6.12 respectively (see below). It seems that the patch in LKML differs a bit from the version that was uploaded in Gitlab, I've done a bit of checking and they seem to be equivalent for the most part but to make sure, can you please build with this commit? @ACupOfLinux 

6.11: https://github.com/CachyOS/linux/commit/29e74505e56f5ec60d46e1e4e9f81feec95fa435
6.12: https://github.com/CachyOS/linux/commit/d3fe2f5167a2deae6f209921bd4c0f3f7c2a8719

**Comment by ACupOfLinux** [comment]
> I have applied the patch from LKML to both 6.11 and 6.12 respectively (see below). It seems that the patch in LKML differs a bit from the version that was uploaded in Gitlab, I've done a bit of checking and they seem to be equivalent for the most part but to make sure, can you please build with this commit? @ACupOfLinux
> 
> 6.11: [CachyOS/linux@29e7450](https://github.com/CachyOS/linux/commit/29e74505e56f5ec60d46e1e4e9f81feec95fa435) 6.12: [CachyOS/linux@d3fe2f5](https://github.com/CachyOS/linux/commit/d3fe2f5167a2deae6f209921bd4c0f3f7c2a8719)

Of Course, It will be in the morning though as I am out right now but thank you for including this patch! :)

**Comment by 1Naim** [comment]
The patch from LKML will now be queued for 6.12.0rc4 and 6.11.5. If the patch works as intended, I think this issue/PR can be closed. I've added a `Suggested-by` tag in the commit to give some deserved credits. Thanks again for bringing this forward to us 😄

**Comment by ACupOfLinux** [comment]
> The patch from LKML will now be queued for 6.12.0rc4 and 6.11.5. If the patch works as intended, I think this issue/PR can be closed. I've added a `Suggested-by` tag in the commit to give some deserved credits. Thanks again for bringing this forward to us 😄

Thank you SO much for including this patch! :)

**Comment by 1Naim** [comment]
@ACupOfLinux Hey Kayden, has the CachyOS kernel been functioning okay? Specifically regarding the monitor quirk patch. There's been a report from a user with what I presume to be an affected monitor not showing up 5120x1440 resolution when using the kernel.

**Comment by ACupOfLinux** [comment]
> @ACupOfLinux Hey Kayden, has the CachyOS kernel been functioning okay? Specifically regarding the monitor quirk patch. There's been a report from a user with what I presume to be an affected monitor not showing up 5120x1440 resolution when using the kernel.

Hello! I am currently building a new PC. Still AMDGPU, but the last time I was on CachyOS it ran great! I will let you know when I get back up, and running! With regards,

**Pull request closed without merging**
