### PR TITLE
Add -fmerge-all-constants

### PR DESCRIPTION
**Pull request by BreadTom**
See https://wiki.gentoo.org/wiki/User:Gso321/My_kernel_setup

### CODE REVIEW

**Review by sirlucjan — COMMENTED** [review]
I'm definitely against it. First, I'm not a fan of anonymous, no-name patches. Second - this comment makes me all the more reluctant to accept it.

``` 
Important
Kernel PROBLEMS: Screen stuck at "Loading initial ramdisk"
Causes: drivers/acpi don't work with -fmerge-all-constants. Potential solutions: Either no ACPI with -fmerge-all-constants or edit ACPI itself (Gigachad move right there :)).```

**Review by ventureoo — COMMENTED** [review]
I will just point out that patches are not placed in the root of the repository, but in the directory of the corresponding version, and preferably in the misc.

**Comment by sirlucjan** [comment]
Another thing I noticed: https://forums.gentoo.org/viewtopic-p-8785310.html?sid=b2702cb99009e846f6b63c07cc820872

This fix looks like a very unstable solution. I believe that it is absolutely not suitable for use "in production".

**Comment by ptr1337** [comment]
I’ll close here since it is really unsafe and would break users acpi.

**Pull request closed without merging**
